version: "3"
services:
  web:
    image:
      php:7.3-apache
    volumes:
      - ./public:/var/www/html
  front-test:
    build:
      context: .
      dockerfile: ./docker/front-test/Dockerfile
    tty: true
    volumes:
      - bucket:/app/node_modules
      - .:/app
volumes:
  bucket:
